import subprocess
import re


# check if ollama is running
def is_ollama_running():
    try:
        result = subprocess.run(["ollama", "list"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        return result.returncode == 0
    except Exception:
        return False


# generate commit message
def generate_commit_message(diff_text: str, model: str = "mistral"):
    # simplify diff content
    lines = [l for l in diff_text.split('\n') if l.startswith(('+', '-'))]
    short_diff = "\n".join(lines[:30])


    # set strict prompt
    prompt = (
        f"Task: Write a 1-line git commit message for this diff.\n"
        f"Rule: Start directly with the message. No intro text.\n"
        f"Diff:\n{short_diff}"
    )


    try:
        # run model
        result = subprocess.run(
            ["ollama", "run", model, prompt],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=30
        )

        if result.returncode != 0:
            return None

        output = result.stdout.strip()


        # extract message using quotes or colon
        match = re.search(r'"([^"]*)"', output)
        
        if match:
            message = match.group(1).strip()
        else:
            if ":" in output:
                message = output.split(":")[-1].strip()
            else:
                lines = [l.strip() for l in output.split('\n') if l.strip()]
                message = lines[-1] if lines else output


        # remove ai filler phrases
        junk_phrases = [
            "the commit message generated by the script is",
            "the generated commit message is",
            "suggested commit message",
            "commit message",
            "here is the message"
        ]
        
        lower_msg = message.lower()
        for junk in junk_phrases:
            if lower_msg.startswith(junk):
                message = message[len(junk):].strip()
                message = re.sub(r'^[:\-\s]+', '', message)


        # final string cleanup
        message = message.strip('"').strip("'").strip().strip('.')

        return message


    except Exception as e:
        print(f"[!] Error: {e}")
        return None